---
#
#
## Template sensors
- platform: template
  sensors:
    unifi_gateway_wan_cpu:
      friendly_name: "CPU"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('sensor.unifi_gateway_wan', 'gw_system-stats').cpu }}"
    unifi_gateway_wan_mem:
      friendly_name: "Memory"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('sensor.unifi_gateway_wan', 'gw_system-stats').mem }}"
    unifi_gateway_wan_ip:
      friendly_name: "WAN IP"
      value_template: "{{ state_attr('sensor.unifi_gateway_wan', 'wan_ip') }}"
    unifi_gateway_wan_download:
      friendly_name: "WAN Download"
      unit_of_measurement: Kbps
      icon_template: mdi:progress-download
      value_template: "{{ (state_attr('sensor.unifi_gateway_wan', 'rx_bytes-r') / 1024) | int }}"
    unifi_gateway_wan_uptime:
      friendly_name: "USG Uptime"
      value_template: >
        {%- set time = state_attr('sensor.unifi_gateway_wan', 'gw_system-stats').uptime | int %}
        {%- set minutes = ((time % 3600) // 60) %}
        {%- set minutes = '{}min'.format(minutes) if minutes > 0 else '' %}
        {%- set hours = ((time % 86400) // 3600) %}
        {%- set hours = '{}hr '.format(hours) if hours > 0 else '' %}
        {%- set days = (time // 86400) %}
        {%- set days = '{}d '.format(days) if days > 0 else '' %}
        {{ 'Less than 1 min' if time < 60 else days + hours + minutes }}
    unifi_gateway_firmware_version:
      friendly_name: "USG Firmware Version"
      icon_template: mdi:database-plus
      value_template: "{{ state_attr('sensor.unifi_gateway_wan', 'gw_version') }}"
    unifi_gateway_www_xput_down:
      friendly_name: "USG Speedtest Download"
      unit_of_measurement: Mbps
      icon_template: mdi:progress-download
      value_template: "{{ state_attr('sensor.unifi_gateway_www', 'xput_down') }}"
    unifi_gateway_www_xput_up:
      friendly_name: "USG Speedtest Upload"
      unit_of_measurement: Mbps
      icon_template: mdi:progress-upload
      value_template: "{{ state_attr('sensor.unifi_gateway_www', 'xput_up') }}"
    unifi_gateway_www_speedtest_ping:
      friendly_name: "USG Speedtest Ping"
      unit_of_measurement: ms
      icon_template: mdi:progress-clock
      value_template: "{{ state_attr('sensor.unifi_gateway_www', 'speedtest_ping') }}"
    unifi_gateway_www_uptime:
      friendly_name: "Internet Uptime"
      value_template: >
        {%- set time = state_attr('sensor.unifi_gateway_www', 'uptime') | int %}
        {%- set minutes = ((time % 3600) // 60) %}
        {%- set minutes = '{}min'.format(minutes) if minutes > 0 else '' %}
        {%- set hours = ((time % 86400) // 3600) %}
        {%- set hours = '{}hr '.format(hours) if hours > 0 else '' %}
        {%- set days = (time // 86400) %}
        {%- set days = '{}d '.format(days) if days > 0 else '' %}
        {{ 'Less than 1 min' if time < 60 else days + hours + minutes }}
    unifi_gateway_wlan_num_user:
      friendly_name: "Users"
      icon_template: mdi:account-multiple
      value_template: "{{ state_attr('sensor.unifi_gateway_wlan', 'num_user') }}"
    unifi_gateway_lan_num_user:
      friendly_name: "Users Lan"
      icon_template: mdi:account-multiple
      value_template: "{{ state_attr('sensor.unifi_gateway_lan', 'num_user') }}"
    unifi_ssid_wifi_users:
      friendly_name: "Wi-Fi ssid"
      value_template: "{{ state_attr('sensor.unifi', 'Wi-Fi') }}"
    unifi_ssid_not_users:
      friendly_name: "NoT ssid"
      value_template: "{{ state_attr('sensor.unifi', 'NoT') }}"
    unifi_wired_users:
      friendly_name: "wired devices"
      value_template: "{{ state_attr('sensor.unifi', 'wired') }}"
    unifi_united_iot:
      friendly_name: United-IoT - Count
      value_template: "{{ state_attr('sensor.unifi', 'United-IoT') }}"
    unifi_united_wifi:
      friendly_name: United-WiFi - Count
      value_template: "{{ state_attr('sensor.unifi', 'United-WiFi') }}"
    unifi_united_guest:
      friendly_name: United-Guest - Count
      value_template: "{{ state_attr('sensor.unifi', 'United-Guest') }}"

# Unifi Gateway sensors // https://github.com/custom-components/sensor.unifigateway
- platform: unifigateway
  host: !secret unifi_host
  port: 8443
  username: !secret unifi_username
  password: !secret unifi_password
  monitored_conditions:
    - vpn
    - lan
    - wan
    - www
    - wlan
    - alerts
    - firmware

# UniFi Sensor ESSID device count (count ap ssid's) https://github.com/RubenDijk/homeassistant/blob/master/README.md
- platform: my_unifi
  username: !secret unifi_username
  password: !secret unifi_password
  url: !secret unifi_url
