---
# Enables a custom component called "versions".
# It is a sensor that fetches the version number of current Home Assistant releases.
#
# https://www.home-assistant.io/integrations/version/
#

########## BETA ##########
# Fetch beta version of HA
- platform: version
  name: Home Assistant Beta versie
  beta: true
  source: pypi

# HassOS version beta
- platform: rest
  resource: https://version.home-assistant.io/beta.json
  name: HassOs version - beta
  value_template: "{{ value_json.hassos.ova }}"
  scan_interval: 3600

# Supervisor version beta
- platform: rest
  resource: https://version.home-assistant.io/beta.json
  name: Supervisor version - beta
  value_template: "{{ value_json.supervisor }}"
  scan_interval: 3600

########## STABLE ##########
# Fetch stable version of HA
- platform: version
  name: Home Assistant Stable versie
  beta: false
  source: pypi

# HassOS version stable
- platform: rest
  resource: https://version.home-assistant.io/stable.json
  name: HassOs version - stable
  value_template: "{{ value_json.hassos.ova }}"
  scan_interval: 3600

# Supervisor version stable
- platform: rest
  resource: https://version.home-assistant.io/stable.json
  name: Supervisor version - stable
  value_template: "{{ value_json.supervisor }}"
  scan_interval: 3600

########## DEV ##########
# Home Assistant version dev
- platform: rest
  resource: https://version.home-assistant.io/dev.json
  name: Home Assistant Dev versie
  value_template: "{{ value_json.homeassistant.default }}"
  scan_interval: 3600

# HassOS version dev
- platform: rest
  resource: https://version.home-assistant.io/dev.json
  name: HassOs version - dev
  value_template: "{{ value_json.hassos.ova }}"
  scan_interval: 3600

# Supervisor version dev
- platform: rest
  resource: https://version.home-assistant.io/dev.json
  name: Supervisor version - dev
  value_template: "{{ value_json.supervisor }}"
  scan_interval: 3600
