---
# Enables a custom component called "versions".
# It is a sensor that fetches the version number of current Home Assistant releases.
#
# https://www.home-assistant.io/integrations/version/
#

########## BETA ##########
# HassOS version beta
- platform: rest
  resource: https://version.home-assistant.io/beta.json
  name: HassOs version - beta
  value_template: "{{ value_json.hassos.ova }}"
  scan_interval: 3600

# Supervisor version beta
- platform: rest
  resource: https://version.home-assistant.io/beta.json
  name: Supervisor version - beta
  value_template: "{{ value_json.supervisor }}"
  scan_interval: 3600

########## STABLE ##########
# HassOS version stable
- platform: rest
  resource: https://version.home-assistant.io/stable.json
  name: HassOs version - stable
  value_template: "{{ value_json.hassos.ova }}"
  scan_interval: 3600

# Supervisor version stable
- platform: rest
  resource: https://version.home-assistant.io/stable.json
  name: Supervisor version - stable
  value_template: "{{ value_json.supervisor }}"
  scan_interval: 3600

########## DEV ##########
# HassOS version dev
- platform: rest
  resource: https://version.home-assistant.io/dev.json
  name: HassOs version - dev
  value_template: "{{ value_json.hassos.ova }}"
  scan_interval: 3600

# Supervisor version dev
- platform: rest
  resource: https://version.home-assistant.io/dev.json
  name: Supervisor version - dev
  value_template: "{{ value_json.supervisor }}"
  scan_interval: 3600
