---
# NTC Temperature
#
# https://esphome.io/components/sensor/ntc.html
#
- platform: ntc
  sensor: temp_resistance_reading
  name: ${name} - Temperature
  unit_of_measurement: "°C"
  accuracy_decimals: 1
  icon: "mdi:thermometer"
  calibration:
    b_constant: 3350
    reference_resistance: 10kOhm
    reference_temperature: 298.15K
