---
# Total Daily Energy Sensor
#
# The total_daily_energy sensor is a helper sensor that can use the energy
# value of other sensors like the HLW8012, CSE7766, etc
# and integrate it over time.
#
# https://esphome.io/components/sensor/total_daily_energy.html
#
platform: total_daily_energy
id: sensor_total_daily_energy
name: "${name} Daily Energy Usage"
device_class: energy
state_class: total_increasing
entity_category: diagnostic
unit_of_measurement: "kWh"
filters:
  # Multiplication factor from W to kW is 0.001
  - multiply: 0.001
