---
# Uptime Sensor
#
# The uptime sensor allows you to track the time the ESP has stayed up for in
# seconds. Time rollovers are automatically handled.
#
# https://esphome.io/components/sensor/uptime.html
#
#
# WARNING! DO NOT USE THIS SENSOR IN HOME ASSISTANT!
#
# I see many of you using this sensor in Home Assistant, but please, don't.
# There is no need to have an update of the uptime, just send the timestamp
# of when the device started ONCE. It will have the same effect and saves
# you system tons of processing and recording.
#
# See, for example, the `uptime_timestamp.yaml` file.
#
platform: uptime
id: sensor_uptime
