---
#
#
- alias: '[Light] - Control office'
  description: >-
    Control the office spots

  id: 7c023074-de44-410b-9745-34dfa030e73b

  use_blueprint:
    path: philips_remote_lights.yaml
    input:
      remote: fa04ee234e1c48a3256d718b57b13f07
      light:
        entity_id: light.shelly_office_spots
