---
# https://www.zigbee2mqtt.io/devices/324131092621.html
#
- alias: '[Light] - Control office'
  description: >-
    Control the office spots

  id: 7c023074-de44-410b-9745-34dfa030e73b

  use_blueprint:
    path: philips_remote_lights.yaml
    input:
      remote: sensor.philips_remote_action
      light:
        entity_id: light.shelly_office_spots
