---
# https://www.zigbee2mqtt.io/devices/E1524_E1810.html
#
- alias: "[Light] - Control apartment kitchen"
  description: >-
    Control the kitchen lights in apartment

  id: 41cee8a5-a1d3-4682-b921-dfbe3e982e60

  use_blueprint:
    path: ikea_round_remote.yaml
    input:
      remote: sensor.keuken_remote_action
      light:
        entity_id: light.apartment_kitchen
