---
# Home Assistant Time Source
#
# The preferred way to get time in ESPHome is using Home Assistant. With the
# homeassistant time platform, the native API connection to Home Assistant will
# be used to periodically synchronize the current time.
#
# https://esphome.io/components/time.html#home-assistant-time-source
#
platform: homeassistant
id: time_homeassistant
