---
# WiFi Info Text Sensor
#
# The wifi_info text sensor platform exposes different WiFi information via
# text sensors.
#
#
platform: wifi_info
ip_address:
  name: "${name} IP Address"
ssid:
  name: "${name} SSID"
bssid:
  name: "${name} BSSID"
