---
# WiFi Info Text Sensor
#
# The wifi_info text sensor platform exposes different WiFi information via
# text sensors.
#
#
platform: wifi_info
ip_address:
  name: "${name} - IP Address"
  icon: mdi:wifi
ssid:
  name: "${name} - Connected SSID"
  icon: mdi:wifi-strength-2
bssid:
  name: "${name} - Connected BSSID"
  icon: mdi:wifi-strength-2
