---
blueprint:
  name: Z2M - Aqara D1 (2 way) remote for cover
  description: |
    Control cover with an Aqara D1 (2 way) remote.

    - single press to open/close cover
  domain: automation
  input:
    remote:
      name: Aqara D1 remote action
      description: 'This must be an "action" event provided by zigbee2mqtt. For example "event.living_dimmer_action"'
      selector:
        entity:
          filter:
            - integration: mqtt
              domain: event
    cover:
      name: Cover
      description: The cover to control
      selector:
        target:
          entity:
            domain: cover

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input remote
    not_from:
      - unavailable
      - unknown

action:
  - variables:
      event: "{{ trigger.to_state.attributes.event_type | default('unknown', true) }}"

  - choose:
      # Cover closing
      - conditions: "{{ event == 'single_left' }}"
        sequence:
          - service: cover.open_cover
            target: !input 'cover'
            data: {}
      # Cover open
      - conditions: "{{ event == 'single_right' }}"
        sequence:
          - service: cover.close_cover
            target: !input 'cover'
            data: {}
