---
# DSMR for ESPHome
#
# DSMR is a custom component that is in fact a DSMR (P1 Port) reader that runs
# fully within ESPHome.
#
# It allows you to expose data from your energy meter directly from ESPHome
# as sensors, or use them within ESPHome for further processing.
#
# https://github.com/zuidwijk/dsmr
#
# This component has been tested and used with DSMR reader boards created
# and sold by Marcel Zuidwijk, which I can highly recommend.
#
# Get yours at: https://www.zuidwijk.com
#
esphome:
  project:
    name: zuidwijk.slimmelezer
    version: "1.0"

sensor:
  - platform: dsmr
    energy_delivered_tariff1:
      name: "${name} - Energy Consumption (Low Tariff)"
    energy_delivered_tariff2:
      name: "${name} - Energy Consumption (High Tariff)"
    power_delivered:
      name: "${name} - Power Actual Consumption"
    electricity_failures:
      name: "${name} - Energy Failures"
      icon: mdi:alert
    electricity_long_failures:
      name: "${name} - Energy Long Failures"
      icon: mdi:alert
    electricity_sags_l1:
      name: "${name} - Energy Sags L1"
    electricity_sags_l2:
      name: "${name} - Energy Sags L2"
    electricity_sags_l3:
      name: "${name} - Energy Sags L3"
    electricity_swells_l1:
      name: "${name} - Energy Swells L1"
    electricity_swells_l2:
      name: "${name} - Energy Swells L2"
    electricity_swells_l3:
      name: "${name} - Energy Swells L3"
    voltage_l1:
      name: "${name} - Instant Voltage L1"
    voltage_l2:
      name: "${name} - Instant Voltage L2"
    voltage_l3:
      name: "${name} - Instant Voltage L3"
    current_l1:
      name: "${name} - Instant Current L1"
    current_l2:
      name: "${name} - Instant Current L2"
    current_l3:
      name: "${name} - Instant Current L3"
    gas_delivered:
      name: "${name} - Gas Delivered"

text_sensor:
  - platform: dsmr
    identification:
      id: dsmr_identification
      name: "${name} - DSMR Identification"
    p1_version:
      id: dsmr_p1_version
      name: "${name} - DSMR Version"
    electricity_tariff:
      id: dsmr_electricity_tariff
      name: "${name} - Energy Tariff"
