---
# Home Assistant backups
#
- alias: '[System] - Make weekly Home Assistant backup'
  description: >-
    Every week a make backups on specific days

  id: 1024a6fc-c717-473b-bc5d-ec917e81666c
  mode: single

  trigger:
    - platform: time
      at: '03:00:00'
  condition:
    - condition: time
      weekday:
        - wed
        - sun
  action:
    - service: hassio.backup_full
      data_template:
        name: Backup {{ now().strftime('%Y-%m-%d') }} running HA version {{ states('sensor.ha_installed_version') }}
