---
# Captive Portal component
#
# The captive portal component in ESPHome is a fallback mechanism for when
# connecting to the configured WiFi fails.
#
# https://esphome.io/components/captive_portal.html
#
captive_portal: ~
