---
# OTA (Over The Air) component
#
# Contains my common Wi-Fi setup.
#
# https://esphome.io/components/ota.html
#
# substitutions:
#   ota_password: !secret esphome_ota_password

ota:
  - platform: esphome
    id: esphome_ota
    # password: "${ota_password}"
