---
# Apartment hall
#
# Control the lights in the apartment hall.
#
substitutions:
  slug: apartment_hall
  name: Hal Appartement
  description: "Node to control the apartment hall light"

esphome:
  project:
    name: klaasnicolaas.shelly1
    version: "1.0"

packages:
  device: !include devices/shelly1.yaml
