---
# Scullery toilet
#
# Control the lights in the scullery toilet.
#
substitutions:
  slug: scullery-toilet
  name: WC Bijkeuken
  description: "Node to control the scullery toilet light"

esphome:
  project:
    name: klaasnicolaas.shelly1
    version: "1.0"

packages:
  device: !include devices/shelly1.yaml
