---
# Scullery lights
#
# Control the lights in the scullery.
#
substitutions:
  slug: scullery-lights
  name: Bijkeuken
  description: "Node to control the scullery lights"

  channel_1: Bijkeuken
  channel_2: Schrobhoek

esphome:
  project:
    name: klaasnicolaas.shelly25
    version: "1.0"

packages:
  device: !include devices/shelly25.yaml
