---
# Server cabinet
#
# It just sends out power data to Home Assistant.
#
substitutions:
  slug: server_cabinet
  name: Serverkast
  description: "This is my configuration for the server cabinet"

esphome:
  project:
    name: klaasnicolaas.blitzwolf_shp2
    version: "1.0"

packages:
  device: !include devices/blitzwolf_shp2.yaml
