---
# Scullery ventilation system
#
# It just sends out power data to Home Assistant.
#
substitutions:
  slug: ventilation-system
  name: Ventilatie
  description: "This is my configuration for the ventilation system"

esphome:
  project:
    name: klaasnicolaas.blitzwolf_shp2
    version: "1.0"

packages:
  device: !include devices/blitzwolf_shp2.yaml
